Modification for Cowell Algorithm migration to Numbakit-ode
Juanlu001/poliastro pull request #11
Opened 2020-12-31 07:24 UTC by DhruvSondhi

Made modifications as mentioned in #1053

2020-12-31 09:08 UTC, DhruvSondhi commented
Just a test right now. More commits coming up:wink:

2020-12-31 09:31 UTC, astrojuanlu commented
Thanks! As I clarified in the chat, let's keep this branch only for the refactor. We'll do the switch in another pull request.

2020-12-31 09:40 UTC, DhruvSondhi commented
These tests work fine ... you can check & confirm the same :smile:

2020-12-31 09:42 UTC, astrojuanlu requested changes
Added a bunch of preliminary comments - also, I guess the actual fixes for the tests are yet to come.

This will need a couple of iterations more.

2020-12-31 09:42 UTC, astrojuanlu commented on pyproject.toml
> +    "numbakit-ode",
Please remove this line for now :)

2020-12-31 09:42 UTC, astrojuanlu commented on src/poliastro/twobody/propagation.py
> +import nbkode
Not needed yet

2020-12-31 09:42 UTC, astrojuanlu commented on src/poliastro/twobody/propagation.py
> +from scipy.integrate import solve_ivp, DOP853
I think this is out of order, `tox -e check` will complain, I think

2020-12-31 09:42 UTC, astrojuanlu commented on src/poliastro/twobody/propagation.py
> +    t0 = 0
Not needed

2020-12-31 09:42 UTC, astrojuanlu commented on src/poliastro/twobody/propagation.py
> +        (0, max(tofs)),
Please remove extra space

2020-12-31 09:43 UTC, astrojuanlu commented
Also, when you finish, please squash the commits into one.

One last question: how are you running the tests? Can you paste the command here?

2020-12-31 09:54 UTC, DhruvSondhi commented
I am running the test with the following command: 
```python
pytest test_propagation.py  #running from inside /src/poliastro/tests/
```

2020-12-31 09:56 UTC, astrojuanlu commented
In that case, please run

```
$ tox -e reformat  # Rewrites the code to follow our style guides
$ tox -e py38  # assuming you're on Python 3.8
```

This will run _all_ the tests. It will take a while and you will discover more failures.

2020-12-31 09:58 UTC, DhruvSondhi commented
> In that case, please run
> 
> ```
> $ tox -e reformat  # Rewrites the code to follow our style guides
> $ tox -e py38  # assuming you're on Python 3.8
> ```
> 
> This will run _all_ the tests. It will take a while and you will discover more failures.

the `py38` here is the `environment` ?

2020-12-31 09:59 UTC, astrojuanlu commented
yep!

2020-12-31 09:59 UTC, astrojuanlu commented
...the tox environment. Not the Python virtual environment.

2021-01-01 20:56 UTC, astrojuanlu commented
Merged manually in 640aebbd324467af5ffffd4a6aa7c89b36e2756a. Thanks @DhruvSondhi!

2021-01-01 20:56 UTC, closed without merging